export let foodData = [
    {
        id: 70,
        category_id: "48",
        image: "https://course.divinecoder.com/images/1727247108.jpg",
        name: "burger",
        price: "344",
        rating: "54",
        rating_count: "567",
        facilities: "best food",
        category_name: "burger",
    },
    {
        id: 88,
        category_id: "51",
        image: "https://course.divinecoder.com/images/1727248664.jpg",
        name: "Tandoori Chicken",
        price: "456",
        rating: "76",
        rating_count: "89",
        facilities: "it is harmful for body",
        category_name: "Tandoori Chicken",
    },
    {
        id: 89,
        category_id: "50",
        image: "https://course.divinecoder.com/images/1727248739.jpg",
        name: "Fish fry",
        price: "325",
        rating: "55",
        rating_count: "100",
        facilities: "Its testfull",
        category_name: "fish fry",
    },
    {
        id: 90,
        category_id: "50",
        image: "https://course.divinecoder.com/images/1727248826.jpg",
        name: "fish fry",
        price: "225",
        rating: "55",
        rating_count: "600",
        facilities: "fish fry",
        category_name: "fish fry",
    },
    {
        id: 31,
        category_id: "44",
        image: "https://course.divinecoder.com/images/1727081881.jpg",
        name: "spring rools",
        price: "900",
        rating: "23",
        rating_count: "13",
        facilities: "best food",
        category_name: "Spring rools",
    },
    {
        id: 35,
        category_id: "44",
        image: "https://course.divinecoder.com/images/1727082062.jpg",
        name: "spring rools",
        price: "678",
        rating: "54",
        rating_count: "21",
        facilities: "best food",
        category_name: "Spring rools",
    },
    {
        id: 59,
        category_id: "47",
        image: "https://course.divinecoder.com/images/1727168130.jpg",
        name: "Shawarma",
        price: "199",
        rating: "50",
        rating_count: "12",
        facilities: "100",
        category_name: "shawarma",
    },
    {
        id: 33,
        category_id: "44",
        image: "https://course.divinecoder.com/images/1727081966.jpg",
        name: "spring rools",
        price: "567",
        rating: "34",
        rating_count: "52",
        facilities: "best food",
        category_name: "Spring rools",
    },
    {
        id: 64,
        category_id: "47",
        image: "https://course.divinecoder.com/images/1727168901.jpeg",
        name: "shawarma",
        price: "334",
        rating: "231",
        rating_count: "34",
        facilities: "best food",
        category_name: "shawarma",
    },
    {
        id: 69,
        category_id: "51",
        image: "https://course.divinecoder.com/images/1727246728.jpg",
        name: "Tandoori Chicken",
        price: "678",
        rating: "45",
        rating_count: "34",
        facilities: "food",
        category_name: "Tandoori Chicken",
    },
];
